/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'knutn' at '7/18/16 4:25 PM' with Gradle 2.14
 *
 * @author knutn, @date 7/18/16 4:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
