CREATE TABLE type (
    id SERIAL PRIMARY KEY,
    name CHARACTER VARYING(254) NOT NULL UNIQUE,
    amount INTEGER NOT NULL
);

CREATE TABLE "user" (
    id SERIAL PRIMARY KEY,
    first_name CHARACTER VARYING(254) NOT NULL,
    last_name CHARACTER VARYING(254) NOT NULL,
    username CHARACTER VARYING(254) NOT NULL UNIQUE,
    email CHARACTER VARYING(255) UNIQUE
);

CREATE TABLE log (
    id SERIAL PRIMARY KEY,
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    user_id INTEGER NOT NULL REFERENCES "user"(id),
    type_id INTEGER NOT NULL REFERENCES type(id)
);
